services:
  - type: web
    name: clinic-billing-backend
    env: python
    plan: free
    buildCommand: |
      pip install -r backend/requirements.txt
      cd backend && alembic upgrade head
      cd frontend && npm install && npm run build
      mkdir -p backend/static && cp -r dist/* backend/static/
    startCommand: cd backend && python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: clinic-billing-db
          property: connectionString
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: SMTP_HOST
        value: sandbox.smtp.mailtrap.io
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USERNAME
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: SENDGRID_API_KEY
        sync: false
      - key: EMAIL_FROM_ADDRESS
        value: no-reply@clinic.com
      - key: CORS_ORIGINS
        value: https://billingsystem-gm9s.onrender.com,http://localhost:5173,http://localhost:5174

databases:
  - name: clinic-billing-db
    plan: free
